# Generated by Django 4.2.6 on 2024-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='fotos_productos/default.png', upload_to='fotos_productos/'),
        ),
    ]
